// GENERE PAR scripts/extract-icons.mjs — ne pas editer a la main.
// Relancer avec : npm run icons
//
// La police est sous-ensemblee aux icones ci-dessous. Une icone ajoutee dans
// le code mais absente de cette liste s'affichera sous forme de texte brut :
// relancer le script apres tout ajout.

export const MATERIAL_SYMBOLS = [
  "add",
  "add_circle",
  "add_reaction",
  "album",
  "arrow_back",
  "arrow_forward",
  "audiotrack",
  "auto_awesome",
  "bar_chart",
  "bookmark",
  "bookmark_add",
  "calendar_add_on",
  "calendar_today",
  "chart",
  "chat_bubble_outline",
  "check",
  "chevron_left",
  "chevron_right",
  "close",
  "computer",
  "dark_mode",
  "delete",
  "description",
  "edit",
  "emoji_events",
  "event",
  "exercise",
  "expand_more",
  "favorite",
  "feed",
  "filter_list",
  "format_quote",
  "group",
  "groups",
  "guitar",
  "headphones",
  "label",
  "layers",
  "library",
  "library_music",
  "light_mode",
  "link",
  "local_fire_department",
  "location_on",
  "lock",
  "menu_book",
  "metronome",
  "more_vert",
  "music_note",
  "open_in_new",
  "person",
  "person_add",
  "person_search",
  "photo_camera",
  "play_arrow",
  "play_circle",
  "playlist_add",
  "queue_music",
  "rate_review",
  "recommend",
  "refresh",
  "repeat",
  "schedule",
  "search",
  "send",
  "setlist",
  "settings",
  "shopping_bag",
  "social",
  "speed",
  "star",
  "stars",
  "timer",
  "trending_up",
  "trophy",
  "tune",
  "tuner",
  "users",
  "vertical_align_top",
  "video",
  "videocam"
] as const;

export const MATERIAL_SYMBOLS_HREF =
  "https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" +
  "&icon_names=" +
  MATERIAL_SYMBOLS.join(",") +
  "&display=block";
